### ISSUE TITLE
Hi i upgrade according to guide but error

### ISSUE THREAD

**Issue by lablnet** [terdia/legato#6]
Hay i update according to your guide then 
copy paste form encrypted files form framework repo its show error

![screenshot 288](https://user-images.githubusercontent.com/27757785/40773176-886ff088-64db-11e8-829b-055f9097b16a.png)

**Comment by terdia** [comment]
Hi @Lablnet, 

this is because there was a typo in that commit which has received a minor update [#fix typo bug](https://github.com/terdia/legato-framework/commit/3c1fdac74988138fcf046fc392fbfd011f4f92ce)

To fix this run 

composer remove legato/framework && composer clearcache &&
composer require legato/framework

**Comment by lablnet** [comment]
@terdia  Thanks you so much resolve
